### ISSUE TITLE
CSS won´t load on https

### ISSUE THREAD

**Issue by DavidWiesner** [lvdmaaten/lvdmaaten.github.io#2]
Hi,

i have discovered an issue in your website https://lvdmaaten.github.io .

When used HTTPS than the CSS files won´t get loaded because they are included via HTTP. I think this could be fixed when using https instead of http in your url-attribute in _config.yml.
regards, 
David

**Comment by lvdmaaten** [comment]
Thanks for letting me know! Fixed by d01c316.

**Comment by wsCJ1** [comment]
How do I change a video to show  the same output?
